environment: development
address: 0.0.0.0
socket: /tmp/thin.sock
timeout: 30
log: "~/apps/alibabify_app/log/thin.log"
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
daemonize: true
servers: 1
